# Generated by Django 4.0.6 on 2022-07-10 11:34

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='billsDB',
            fields=[
                ('date', models.DateField(max_length=20)),
                ('balance', models.IntegerField()),
                ('bill_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'logbook_billsDB',
            },
        ),
        migrations.CreateModel(
            name='testDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_date', models.DateTimeField(auto_now=True)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('now_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('test_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='unitsDB',
            fields=[
                ('unit_no', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(default='A', max_length=1)),
            ],
            options={
                'db_table': 'logbook_unitsDB',
            },
        ),
        migrations.CreateModel(
            name='accountsDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('bday', models.DateField(max_length=10)),
                ('occu', models.CharField(blank=True, max_length=50, null=True)),
                ('contact', models.CharField(blank=True, max_length=20, null=True)),
                ('unit_no', models.IntegerField(blank=True, null=True)),
                ('prop_type', models.CharField(blank=True, choices=[('1', '1 Bedroom'), ('2', '2 Bedroom')], max_length=1, null=True)),
                ('total_balance', models.IntegerField(default=0)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='historyDB',
            fields=[
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('pay_for', models.DateField(max_length=20)),
                ('amount', models.IntegerField()),
                ('unit_no', models.IntegerField()),
                ('prop_type', models.CharField(max_length=20)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('bill_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Logbook.billsdb')),
            ],
            options={
                'db_table': 'logbook_historyDB',
            },
        ),
        migrations.AddField(
            model_name='billsdb',
            name='tenant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
    ]
